keys:
  - &admin_sof age1az8zp8752k9jn4njav797p5rt2s36kj502ktapz9nxfk46l28cws3u4jy4
  - &admin_sof_laptop age195ara20a3clpdrp8zlrnjldv207d294u82hv2dgma4269dprys3sg6682x
  - &server_desktop age1uz8ruvmn5yaceg3d9sttk438wrc57qsqhpldss7ec8hfq3ev6p2qcn47r9
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_sof
          - *admin_sof_laptop
          - *server_desktop
  - path_regex: secrets/desktop/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_sof
          - *server_desktop
  - path_regex: secrets/laptop/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_sof
          - *admin_sof_laptop
          - *server_desktop
