atuin: ENC[AES256_GCM,data:7ZtbHBM4R/mYjsihQhrHrWLEykSfiJARAu9TzRZXZK1lyr5P6SLDQ5LXb0j/pjjzrEho6lzH0zH4opc9hDpGNg==,iv:sCSjgynEIw0JPQLjUAGCVf/U8a3WoA+llZd8rxaahxE=,tag:ncU/xzf2BjLi8kWIKY+TDw==,type:str]
tmate: ENC[AES256_GCM,data:cWaQeFydh8S7EwDFuiejQ7+WaJm09OCf0bQjJsJ+,iv:G1Be+sRzi2ZuC6XTLfu3ubWd+UN4LEm4i9Ib47Yyr0I=,tag:YbyfafXquz/RWBY7Z/pBpA==,type:str]
cachix-activate-token: ENC[AES256_GCM,data:z1DOloVYpUC5i48MH91Ll2Lga2P1rLiMi7WA0yDuo2Kb3B/VgMLnT+R6BdxPfFXfIVRv3wkKD+ax6ysVAG4sncEnuR2JyLMMDZUi82Y1YAev1E5UhcFybQ45aV6eGfVaZ762k85O8e8MnHsRUohK/OEUfcqphrevYdN5f3+D3b7Yelgi2vVGhmAM5mLZYkTkeT8GMEb4ctczgh4JQBN0hSS1+OSAjrQooJlfGZoFGw==,iv:fo3XSW9JcJ6KIknv8vw/dvQ4TRg1CUpt8xUhVRrfLmo=,tag:+OiTDG42cibdPaFRhNLsgg==,type:str]
cachix-auth-token: ENC[AES256_GCM,data:PDMYaSzmlSP/i8luV29YTm6Ad2DY3dciFNsJxumukVWw8fbmXbz7N5JbMuaY4yjv3xUrpHU/d7dia9MFwnEpSLZO4skLfY2IyFxHftkk4G0fk6cedzrovdjKqYPQWBo868lBDmIIOQn3ILRYoWFRyZJeM09tmP0Q+NLlHAALtkI5fRCA/O0FmTL7tW4PKvgFIJQzPuwF5I1a8ZoJVcbAV7ERBpfmk8k=,iv:/UUsdSvFfBdgjoN+M+r/igJMa9rc1XgMvsXxPGL2C2Y=,tag:zNhd3oKfmZd8cC2PFN85Xg==,type:str]
cachix-agent-token: ENC[AES256_GCM,data:Suu+OyyhKBM4rcuO2C3IoVGIfU5eSvq6r2AnZaYJmwjVt7GRzUtFmip/RcPumISgx2yisb7j4ofZxInqJUqOns3DiUSqyj1hOISzxYrioQv8pIXjuv4p7Pw53GwxUgHR98m8AK3FyZmfAI/BWe+ykIj/Qevsbbo2uFmJttZYLYTgLtDoQbhw/6zmHoOTAaVHB/86fujp4bCq38qzv3vBFyy7VlGaWr7R,iv:IUa4jmDIX02LWT/0cx6d0LHXlaDCaL2GLHpt8aV+iqg=,tag:sKdYH6dqTuvSt8KEG2HvqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1az8zp8752k9jn4njav797p5rt2s36kj502ktapz9nxfk46l28cws3u4jy4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRnVQRHQvanVRWXpSMHMr
            SVQ4MC9ZNVM0NC80a011TkkwLy9BNCtHd1YwCm1nS1pEcCtETU1VUGxLdjVxWVFM
            TVA4S0ErcTdUbzQwRVdjMVFRYThnVm8KLS0tIGNVMldyZGJiWG5VY2w0WVB6TUZW
            Q0dRS2xQRkNiYm9iSHltTkJUK0FMQkkKhsA/cLFcD6fvuHYfIZ1Gp7ha8O39tYBm
            LyvZvaDVqJPS3mHdqXOn6wBXgu2UGRSy2bK8dHcj2Vn9qgvpZu1fXw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1uz8ruvmn5yaceg3d9sttk438wrc57qsqhpldss7ec8hfq3ev6p2qcn47r9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SEVJWU15ZkdqWlpQdlpT
            RmdkM0VvZ3BsL25LMXFaRkpXNk1Cd0t0NmlVCnNxRm5RRGwzejdNUmJVSDZ2Ritw
            dTB4d0lBN2gvL1BPMmxTbzcrRzd3d3cKLS0tIDRYaklMOFNhY3k3c1ZQQk9NQllp
            R1dXbGo4bnNKSGFuK3dXTzIzc0gzejgKVI/P2SKYkalSw+jYFpuSrftEMV2gDJwr
            +FmXk9Zn7LGiowdBEQ1Ec1mdP4vZ9qaLLlOrmcJoWH+cIgL0rGPO9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-26T05:14:36Z"
    mac: ENC[AES256_GCM,data:E5KviyIH6hkCuRvIZi5oidNiwImkOIwSYR8e9MrTZpX4hJUgvX8XkzMiBBZ3m9P+PvfjK1Y8jfWfNk9InKqYw76CdX0BbejEOTbT6uAQUUl84ZIfsvDvKxZJuRvjK96IlIpXBW/MVGyA/RUyPQJaFZRXeHOsgFF3rz9S6sgQlRE=,iv:sHN3XRlgWCQBaa3W7CZn5NzTidIlmKv8ztXopPUvRfo=,tag:9JROwFwDZ/tiZUjDD6NNmA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
